binop_separator = "Back"
fn_single_line = true
#error_on_line_overflow = true
#error_on_unformatted = true
force_multiline_blocks = true
imports_layout = "Horizontal"
max_width = 110
match_block_trailing_comma = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
overflow_delimited_expr = true
reorder_imports = true
reorder_modules = false
trailing_comma = "Never"
use_small_heuristics = "Off"
unstable_features = true
normalize_comments = true
